### ISSUE TITLE
Type 'video/x-flv' not being shown

### ISSUE THREAD

**Issue by swapagarwal** [108anup/Youtube-Downloader---PHP---Online#1]
You have used [strstr](http://php.net/manual/en/function.strstr.php) which returns false if needle is not found.
This breaks the logic you are using (searching for ';' and taking the before ';' part) in case of type="video/x-flv".

**Comment by 108anup** [comment]
Done!

**Comment by 108anup** [comment]
Thanks for Pointing this.
